### ISSUE TITLE
Can't get Smart.Format 2.3 working

### ISSUE THREAD

**Issue by shawndotey** [axuno/SmartFormat.NET#113]
2.3 or Above
Running on .NET Framework 4.5.1

From your documentation:
```
 var addrList = new[] { new { Name = "Jim", Address = new { City = "New York", State = "NY" } } };
 var test = Smart.Format("{Name} from {Address.City}, {Address.State}", addrList);
```

**Should Output**: `"Jim from New York, NY"`
**Outputs**: `" from , "`

2.2.0 Works as expected.

Thanks!

**Comment by axunonb** [comment]
Just checked with v2.3.1 and .Net Framework 4.5.1 in a new project: cannot reproduce the false output, sorry.

**Comment by axunonb** [comment]
Did catching the exception shed some light into your issue?

**Comment by axunonb** [comment]
Closing after no response

**Comment by shawndotey** [comment]
Sorry but I do not have time to test, I am using 2.2.0 instead.

**Comment by misterm84** [comment]
I know this is a closed topic, but in case it helps anyone who googles their way here, I had a similar issue after using Nuget to get MailMergeLib (which has SmartFormat as a dependency) - in dev everything was happy but on deploying the merge fields output empty strings.

Initially, I thought the problem was with that library, so used SmartFormat directly but still had the same issue.
After turning on the errors, I got "Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0 ..."
It seems to be that 2.3.0 and 2.3.1.1 is expecting to use Newtonsoft.Json 11 wheras my application was using Newtonsoft.Json 12.0.1

I was able to get SmartFormat working by upgrading to latest version (2.4.1), which also expect to use Newtonsoft.Json 12.0.1

**Comment by axunonb** [comment]
Thanks a lot for this very useful hint
